services:
  # Python Backend Service
  - type: web
    name: disasterguard-backend
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm && python -m spacy download xx_ent_wiki_sm
    startCommand: gunicorn app:app --host 0.0.0.0 --port $PORT
    rootDir: ./python_service
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src

  # Node.js Frontend Service  
  - type: web
    name: disasterguard-frontend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: ./node_backend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
